<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;A0UGRH47eCl7ImA9WhJaEUQ.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/3055/comments/full/2</ns0:id><ns0:author>
			<ns0:name>mseaborn@chromium.org</ns0:name><ns0:uri>/u/mseaborn@chromium.org/</ns0:uri></ns0:author><ns0:content type="html">The full traceback is:

Stderr for nacl_glibc.run_gdb_call_from_gdb_test:
======================================================================
Traceback (most recent call last):
  File "/mnt/data/b/build/slave/lucid-32-glibc-opt/build/native_client/tests/gdb/call_from_gdb.py", line 18, in &lt;module&gt;
    gdb_test.RunTest(test, 'call_from_gdb', os.environ['GDB_TEST_GUEST'])
  File "/mnt/data/b/build/slave/lucid-32-glibc-opt/build/native_client/tests/gdb/gdb_test.py", line 262, in RunTest
    test_func(gdb)
  File "/mnt/data/b/build/slave/lucid-32-glibc-opt/build/native_client/tests/gdb/call_from_gdb.py", line 12, in test
    assert gdb.ResumeCommand('continue')['reason'] == 'breakpoint-hit'
  File "/mnt/data/b/build/slave/lucid-32-glibc-opt/build/native_client/tests/gdb/gdb_test.py", line 232, in ResumeCommand
    status, items = self._GetLastExecAsyncRecord(self._GetResponse())
TypeError: 'NoneType' object is not iterable

[  FAILED  ] nacl_glibc.run_gdb_call_from_gdb_test (540 ms)</ns0:content><ns0:updated>2012-10-02T17:33:45.000Z</ns0:updated><ns0:published>2012-10-02T17:33:45.000Z</ns0:published><ns2:updates /><ns0:title>Comment 2 by mseaborn@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=3055#c2" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/3055/comments/full/2" rel="self" type="application/atom+xml" /></ns0:entry>