<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;D0MBRn47eCl7ImA9WhNVGEo.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/3237/comments/full/2</ns0:id><ns0:author>
			<ns0:name>bugdro...@chromium.org</ns0:name><ns0:uri>/u/101788990881243245974/</ns0:uri></ns0:author><ns0:content type="html">The following revision refers to this bug:
    http://src.chromium.org/viewvc/native_client?view=rev&amp;revision=10521

------------------------------------------------------------------------
r10521 | halyavin@google.com | 2012-12-30T13:48:59.269023Z

Changed paths:
   M http://src.chromium.org/viewvc/native_client/trunk/src/native_client/tests/debug_stub/debug_stub_test.py?r1=10521&amp;r2=10520&amp;pathrev=10521

Debug stub: fix test_interrupt test.

The fix ensures that program is interrupted inside test_interrupt function
where there are no syscalls.

BUG= http://code.google.com/p/nativeclient/issues/detail?id=3237
TEST= run_debug_stub_test
Review URL: https://codereview.chromium.org/11722002
------------------------------------------------------------------------</ns0:content><ns0:updated>2012-12-30T13:50:57.000Z</ns0:updated><ns0:published>2012-12-30T13:50:57.000Z</ns0:published><ns2:updates /><ns0:title>Comment 2 by bugdro...@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=3237#c2" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/3237/comments/full/2" rel="self" type="application/atom+xml" /></ns0:entry>