<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;CU4BQH47eCl7ImA9WxNWE0U.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/111/comments/full/2</ns0:id><ns0:author>
			<ns0:name>b...@google.com</ns0:name><ns0:uri>/u/105678638446503189415/</ns0:uri></ns0:author><ns0:content type="html">Here's my attempt to repro this, but the program outputs a reasonable error message:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

so my hypothesis that it was the default exception handler getting an exception was 
wrong.

could you provide a small example that reproduces the "terminate called recursively" 
message?</ns0:content><ns0:updated>2009-10-12T21:45:51.000Z</ns0:updated><ns0:published>2009-10-12T21:45:51.000Z</ns0:published><ns2:updates>
			<ns2:status>NeedMoreInfo</ns2:status></ns2:updates><ns0:title>Comment 2 by b...@google.com</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=111#c2" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/111/comments/full/2" rel="self" type="application/atom+xml" /></ns0:entry>