<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;DUYEQ347eCl7ImA9WhRQE00.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/2448/comments/full/6</ns0:id><ns0:author>
			<ns0:name>nfulla...@google.com</ns0:name><ns0:uri>/u/118309011164612460950/</ns0:uri></ns0:author><ns0:content type="html">Did some local stress testing on my win7 x64 box.
Modified CallOnMainThreadStress to launch 20 threads, each thread performing CallOnMainThread 1,000,000 times.  Launched this nexe (without pyauto) multiple times under 4 simultaneous tabs and let it cook on a z600 w/ 8 physical, 16 logical cores.  Ran this a couple times and all instances passed.
Then tried 4 threads, each performing CallOnMainThread 10,000,000 times.  Again launched under 4 simultaneous threads.  Ran this a couple times and all instances passed.
If there was some flake in CallOnMainThread() thread safety I'd expect it to show up here.  I'm beginning to suspect it could be a start-up issue, or caused by earlier surf-aways, or caused by other nexe tests that run simultaneously with pyauto.
</ns0:content><ns0:updated>2011-12-08T01:18:22.000Z</ns0:updated><ns0:published>2011-12-08T01:18:22.000Z</ns0:published><ns2:updates /><ns0:title>Comment 6 by nfulla...@google.com</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=2448#c6" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/2448/comments/full/6" rel="self" type="application/atom+xml" /></ns0:entry>