<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;CkMGQH47eCl7ImA9WhZSF00.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/1596/comments/full/4</ns0:id><ns0:author>
			<ns0:name>mseaborn@chromium.org</ns0:name><ns0:uri>/u/mseaborn@chromium.org/</ns0:uri></ns0:author><ns0:content type="html">Following on from the previous comment:  This causes gyp_tests to fail with:

@@@BUILD_STEP gyp_tests@@@
+ python trusted_test.py --config Release
python: can't open file 'trusted_test.py': [Errno 2] No such file or directory

because "cd native_client" does not happen.</ns0:content><ns0:updated>2011-04-01T23:27:01.000Z</ns0:updated><ns0:published>2011-04-01T23:27:01.000Z</ns0:published><ns2:updates /><ns0:title>Comment 4 by mseaborn@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=1596#c4" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/1596/comments/full/4" rel="self" type="application/atom+xml" /></ns0:entry>